#!/bin/sh

# Run Prettier on staged files
npx prettier --write $(git diff --cached --name-only --diff-filter=ACM | grep '\.\(js\|ts\|vue\|css\|json\|md\)$')

# Stage the modified files after formatting
git add -u

# Continue with the commit
exit 0
